### ISSUE TITLE
Get problems while preprocessing

### ISSUE THREAD

**Issue by BlairLeng** [cr333/OmniPhotos#26]
I did download all of those binary files from here:https://github.com/cr333/OmniPhotos/releases/download/v1.1/OmniPhotos-v1.1-win10-x64.zip

And I did put ffmpeg.exe into system Path. However, Im getting errors saying this below: 

$ ./preproc/preproc.exe -c preproc-config-template.yaml
[23276] Failed to execute script 'main' due to unhandled exception!
Traceback (most recent call last):
  File "main.py", line 24, in <module>
  File "preproc_app.py", line 39, in __init__
  File "data_preprocessor.py", line 32, in __init__
  File "abs_preprocessor.py", line 70, in __init__
  File "abs_preprocessor.py", line 225, in load_origin_data_info
  File "ffmpeg\_probe.py", line 20, in probe
  File "subprocess.py", line 800, in __init__
  File "subprocess.py", line 1207, in _execute_child
FileNotFoundError: [WinError 2] 

![image](https://user-images.githubusercontent.com/25675774/209557780-5deee940-27b7-426c-9ff0-926714d7577a.png)

**Comment by BlairLeng** [comment]
Can somebody help me?

**Comment by cr333** [comment]
Based on the stack trace, it seems like the problem lies here:
https://github.com/cr333/OmniPhotos/blob/b8aa4c90b87b87b087bca8de3cf0e2b6d13f84da/Python/preprocessing/abs_preprocessor.py#L223

Please make sure that `self.input_path` exists by following this step from the `README.md` file:
> 2. Copy the `preproc-config-template.yaml` template from the preprocessing binary folder to the same directory as the video, and update the `preprocessing.input_path` setting in it to the name of your video.

Please let me know if this helps or if you already figured out a solution (and what you did to fix this problem). Thanks.
